feed/urls.py
from django.urls import path
from .views import HomePageView, PostDetailView, AddPostView

app_name = 'poptart'

urlpatterns = [
    path('', HomePageView.as_view(), name='index'),
    path('details/<int:pk>/', PostDetailView.as_view(), name='detail'),
    path('post/', AddPostView.as_view(), name='post'),
]

poptart/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

from feed import urls as feed_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(feed_urls, namespace='feed'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feed/models.py
from django.db import models
from sorl.thumbnail import ImageField


class Post(models.Model):
    title = models.CharField(max_length=25, blank=False, null=False)
    text = models.CharField(max_length=140, blank=False, null=False)
    image = models.ImageField()

    def __str__(self):
        return self.text

feed/forms.py
from django import forms


class PostForm(forms.Form):
    title = forms.CharField()
    text = forms.CharField(label='Description')
    image = forms.FileField()

feed/views.py
from django.contrib import messages
from django.views.generic import TemplateView, DetailView, FormView

from .forms import PostForm
from feed.models import Post


class HomePageView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts'] = Post.objects.all().order_by('-id')
        return context


class PostDetailView(DetailView):
    template_name = 'details.html'
    model = Post


class AddPostView(FormView):
    template_name = 'new_post.html'
    form_class = PostForm
    success_url = '/'

    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        # Create new post
        new_object = Post.objects.create(
            title=form.cleaned_data['title'],
            text=form.cleaned_data['text'],
            image=form.cleaned_data['image']
        )
        messages.add_message(self.request, messages.SUCCESS,
                             ' succesfully added post to Poptart 🧁')
        return super().form_valid(form)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Poptart 🧁{% endblock title %} </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" 
    rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" 
    crossorigin="anonymous">
</head>
<body>
    
    {% if messages %}
    {% for message in messages %}
    <div class="bg-{% if message.tags %}{{message.tags}}{% else %}primary {% endif %} bg-gradient text-center text-white py-4"> {{ message }} </div>
    {% endfor %}
    {% endif %}
    
    {% include 'includes/navbar.html' %}

    
      <div class="container">
    {% block body %} {% endblock %}
      </div>
</body>
</html>

templates/details.html
{% extends 'base.html' %}
{% block title %}{{object.title}} 🧁 | {{object.text|truncatechars:37}}{% endblock title %}
{% block body %} 
<div class="row">
    <div class="col-sm-10 offset-sm-1 pt-5 py-5">
        <h1> {{post.title}} </h1>
        {{object.text}}
        <img class="img-fluid rounded" src='{{object.image.url}}' style='width: 100%; height: auto;'/>
    </div>
</div>

{% endblock body %}

templates/home.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block body %}
    <div class="row">
    {% for post in posts  %}
        <div class="col-sm-6 col-md-3">
            <div class="card mb-4 mt-4" style="width: 18rem;">
                {% thumbnail post.image "200x200" crop="center" as im %}
                    <img src="{{im.url}}" class="card-img-top" alt="{{post.text}}">
                {% endthumbnail %}
                <div class="card-body">
                    <h5 class="card-title">{{post.title}} 🧁</h5>
                    <p class="card-text">{{post.text|truncatechars:25}} </p>
                    <a href="{% url 'poptart:detail' post.id %}" class="btn btn-primary">View full image</a>
                </div>
            </div>
        </div>
        {% empty %}
        <div class="col-sm-6 offset-3 text-center py-5 my-5">
            <h3> Welcome to Poptart 🧁 </h3>
            <p> Add your first post </p>
            <a href="{% url 'poptart:post' %}" class="btn btn-lg btn-primary">Add post</a>
    {% endfor %}
    </div>
{% endblock body %}

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Poptart 🧁</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'poptart:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'poptart:post' %}">Add new post</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

templates/new_post.html
{% extends 'base.html' %}
{% block title %}Add post {% endblock title %}
{% block body %}
<form method='post' action="" enctype="multipart/form-data" class="col-sm-4 offset-4 py-5 my-5">
    <h2> Upload an image! </h2>
    {% csrf_token %}
    {{form.as_p}}
    <div>
        <button class="btn btn-success btn-lg" type="submit"> Add post </button>
    </div>
</form>
{% endblock body %}